# Autor: Leticya Danielly
# Data : 12/08/2026
### Configuração do pytest para o projeto ###

[pytest]
testpaths = tests
pythonpath = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = -v --html=relatorio.html --self-contained-html --capture=sys

markers =
    nivel1: Suíte de testes do Nível 1
    nivel2: Suíte de testes do Nível 2
    nivel3: Suíte de testes do Nível 3